name: Get License Request

on: workflow_dispatch # 只能手动触发

jobs:
  get-activation-file:
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Activation File
        id: getManualLicenseFile
        # 这一步会生成 .alf 文件
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
